### ISSUE TITLE
エラー:no such file or directory, fishについて

### ISSUE THREAD

**Issue by eightfx** [takeokunn/fish-repl.el#1]
使用環境: mac
ログインシェル: fish
emacsのinit.elにrequireし、fish-replを実行すると次のようなエラーが出る。
「apply: Searching for program: No such file or directory, fish」

fish shellはインストールされているが上のようなエラーで使用することができない。

**Comment by takeokunn** [comment]
@eightfx 
自分の手元では正常に動きました

多分ですが、emacsからfishを実行する際にpathが通ってないのが問題だと思います。

1.  `fish-repl-exec-command` の最初の "fish" を `/usr/local/bin/fish`のようにpathを通してあげる

`(setq fish-repl-exec-command "/usr/local/bin/fish")`
https://github.com/takeokunn/fish-repl.el/blob/main/fish-repl.el#L49-L53

3. `exec-path-from-shell` を使ってpathを通してあげる

自分は以下のように設定しています
https://github.com/takeokunn/.emacs.d/blob/master/index.org#exec-path-from-shell

**Comment by eightfx** [comment]
解決しました。ありがとうございます。
